project_id = "xuhvlomytegdbifziilf"

[functions.send-order-email]
verify_jwt = false

[functions.ai-nutrition]
verify_jwt = false

[functions.ai-consultation-intake]
verify_jwt = false

[functions.seed-catalog]
verify_jwt = false

[functions.ai-recommendation]
verify_jwt = false
